export const RESPONSES = {
  RECORD_ALREADY_EXISTS: 'RECORD_ALREADY_EXISTS',
  AUTHENTICATION_FAILED: 'AUTHENTICATION_FAILED',
  RECORD_DOES_NOT_EXIST: 'RECORD_DOES_NOT_EXIST',
  INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',
  FILE_SIZE_EXCEEDED: 'FILE_SIZE_EXCEEDED',
};
